### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by gagangupta1404** [MLogdberg/APIManagementARMTemplateCreator#131]
Aggregation exception thrown, se following exceptions for more information
Exception: Object reference not set to an instance of an object.
   at APIManagementTemplate.Models.DeploymentTemplate.AddAPIManagementInstance(JObject restObject)
   at APIManagementTemplate.TemplateGenerator.<GenerateTemplate>d__26.MoveNext()

**Comment by Abakion-ALJ** [comment]
I also have this problem, have you find a solution for the error
