### ISSUE TITLE
DeploymentTemplate.cs:line 205 - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mikermesh** [MLogdberg/APIManagementARMTemplateCreator#21]
### DeploymentTemplate.cs:line 205 - Object reference not set to an instance of an object
____

- Commit: ea0cd95

- Command: Get-APIManagementTemplate -APIManagement APIResourceName -ResourceGroup ResourceGroup -SubscriptionId SubId

- Error:
Aggregation exception thrown, 
Exception: Object reference not set to an instance of an object.
   at APIManagementTemplate.Models.DeploymentTemplate.AddAPIManagementInstance(JObject restObject) in C:\_Src\Sdbx\APIManagementARMTemplateCreator\APIManagementTemplate\Models\DeploymentTemplate.cs:line 205
   at APIManagementTemplate.TemplateGenerator.<GenerateTemplate>d__11.MoveNext() in C:\_Src\Sdbx\APIManagementARMTemplateCreator\APIManagementTemplate\TemplateGenerator.cs:line 58

**Comment by MLogdberg** [comment]
Hi,
Not sure what you are having problems with is it with this change or in general?

**Comment by mikermesh** [comment]
@MLogdberg We found the issue...it was related to a policy in the API Management configuration...not related to the template creator. I'm closing the issue...thanks for the feedback.

**Comment by MLogdberg** [comment]
Thanks  @mikermesh!
